sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - docker build  -f 06-ci/test/Dockerfile  -t wordpress06   06-ci

script:
    - docker run -d --name wordpress06   wordpress06
    - sleep 60
    - IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' wordpress06) ; echo http://$IP:80/ > url
    - cat url  |  xargs -t -n 1 curl -v --retry 5 --retry-max-time 120 -o result-wordpress06

    - echo "==> Validating the test results..."
    - grep '<title>ANSIBLE_TEST' result-wordpress06
